server:
  port: 8080
  error:
    whitelabel:
      enabled: false  # false : 기본 error 페이지 비활성화 

spring: 
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/humble_project?serverTimezone=UTC&characterEncoding=UTF-8
    username: root  
    password: jt67f7!@
    
mybatis:
  config-location: classpath:sqlmap/sqlmap-config.xml
  mapper-locations: classpath*:sqlmap/mappers/**/*.xml
  type-aliases-package: com.ipbyhj.dev
  
